name: Docker Image CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Build the Docker image
      run: docker build . --file Dockerfile -t catalogservice:2.0
    - name: tag docker image
      run: docker tag catalogservice:2.0 ghcr.io/vishal1920/catalogservice:2.0
    - name: push docker image
      run: docker push ghcr.io/vishal1920/catalogservice:2.0
